### ISSUE TITLE
telegraf error

### ISSUE THREAD

**Issue by reli3** [mihailescu2m/powerwall_monitor#26]
2022-01-02T01:26:15Z E! [inputs.http] Error in plugin: [url=http://pypowerwall:8675/api/meters/aggregates]: Get "http://pypowerwall:8675/api/meters/aggregates": dial tcp: lookup pypowerwall: Temporary failure in name resolution,
2022-01-02T01:26:20Z E! [inputs.http] Error in plugin: [url=http://pypowerwall:8675/api/meters/aggregates]: Get "http://pypowerwall:8675/api/meters/aggregates": dial tcp 172.18.0.4:8675: connect: connection refused,
2022-01-02T01:26:20Z E! [inputs.http] Error in plugin: [url=http://pypowerwall:8675/strings]: Get "http://pypowerwall:8675/strings": dial tcp 172.18.0.4:8675: connect: connection refused

Unable to pull data

**Comment by reli3** [comment]
@jasonacox any suggestions? Thanks

**Comment by jasonacox** [comment]
Hi @reli3  - I made quite a few edits and accepted a few PRs ([#1](https://github.com/jasonacox/powerwall_monitor/pull/1) and [#2](https://github.com/jasonacox/powerwall_monitor/pull/2)) that I need to submit as PRs here too.  For now, I suggest you try this version: https://github.com/jasonacox/powerwall_monitor 

I suspect the error is related to the pypowerwall section in powerwall.yml:
```yml
    pypowerwall:
        image: jasonacox/pypowerwall:latest
        container_name: pypowerwall
        hostname: pypowerwall
        restart: always
        ports:
            - target: 8675
              published: 8675
              mode: host
        environment:
            PW_PASSWORD: "password"
            PW_EMAIL: "email@example.com"
            PW_HOST: "192.168.91.1"
            PW_TIMEZONE: "America/Los_Angeles"
            PW_DEBUG: "yes"
```
Or it is in the `telegraf.conf` inputs section:

```
[[inputs.http]]
	urls = [
		"http://pypowerwall:8675/aggregates",
		"http://pypowerwall:8675/soe",
		"http://pypowerwall:8675/strings"
	]
	method = "GET"
	insecure_skip_verify = true
	timeout = "4s"
	data_format = "json"
```
